apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: autoscaler
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
